In [19]:
import sys

# EDIT THIS
sys.path.append('/Users/carterdemars/Desktop/tetris-getting-started-main/submission/')

from submission.sample_agent import SelectedAgent
from submission.tetris.game import Game

from tqdm import tqdm
import numpy as np

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [20]:
agent = SelectedAgent()

In [21]:
GAME_SEED = 0
NUM_TRIALS = 2

In [22]:
scores = {}
for i in tqdm(range(NUM_TRIALS)):
    w = np.random.randn(5)
    agent = SelectedAgent(w)
    game = Game(agent, seed=GAME_SEED)
    results = []
    async for item in game.run():
        results.append(item)
    scores.setdefault(game.score, []).append(w)

  0%|          | 0/2 [00:00<?, ?it/s]

[0 4 0 4 4]
[0 4 0 4 6]
[0 6 2 4 6]
[0 4 0 4 4]
[0 4 0 4 6]
[0 6 2 4 6]
[0 4 0 4 4]
[0 4 0 4 6]
[0 6 2 4 6]
[0 4 0 4 2]
[0 4 0 4 5]
[0 6 2 4 6]
[0 4 0 4 2]
[0 4 0 4 5]
[0 6 2 4 6]
[0 4 0 4 2]
[0 4 0 4 5]
[0 6 2 4 6]
[0 4 0 4 4]
[0 4 0 4 6]
[0 6 2 4 6]
[0 4 0 4 4]
[0 4 0 4 6]
[0 6 2 4 6]
[0 4 0 4 4]
[0 4 0 4 6]
[0 6 2 4 6]
[0 4 0 4 3]
[0 4 0 4 6]
[0 6 2 4 3]
[0 4 0 4 3]
[0 4 0 4 6]
[0 6 2 4 3]
[0 4 0 4 4]
[0 4 0 4 6]
[0 6 2 4 6]
[0 4 0 4 4]
[0 4 0 4 6]
[0 6 2 4 6]
[0 4 0 4 4]
[0 4 0 4 6]
[0 6 2 4 6]
[0 4 0 4 2]
[0 4 0 4 5]
[0 6 2 4 6]
[0 4 0 4 2]
[0 4 0 4 5]
[0 6 2 4 3]
[0 4 0 4 2]
[0 4 0 4 5]
[0 6 2 4 3]
[0 4 0 4 4]
[0 4 0 4 6]
[0 6 2 4 6]
[0 4 0 4 4]
[0 4 0 4 6]
[0 6 2 4 6]
[0 4 0 4 4]
[0 4 0 4 6]
[0 6 2 4 6]
[0 4 0 4 3]
[0 4 0 4 6]
[0 6 2 4 3]
[0 4 0 4 3]
[0 4 0 4 3]
[0 6 2 4 3]
[0 8 0 8 4]
[0 8 0 8 6]
[ 0 10  2  8  8]
[ 0 10  2  8  6]
[0 9 1 8 8]
[ 0 10  2  8  6]
[0 9 1 8 4]
[0 8 0 8 6]
[ 0 11  3  8  8]
[ 0 10  2  8  4]
[0 9 1 8 7]
[ 0 10  2  8  6]
[ 0 10  2  8  4]
[0 9 1 8 7]
[ 0 1

 50%|█████     | 1/2 [00:01<00:01,  1.23s/it]

[ 0 99 11 88 14]
[ 0 94  6 88 18]
[ 0 93  5 88 14]
[-1 96  8 88  8]
[ 0 91  3 88 18]
[ 0 96  8 88 11]
[-1 96  8 88  8]
[ 0 91  3 88 18]
[ 0 96  8 88 11]
[ 0 92  4 88 18]
[ 0 91  3 88 20]
[ 0 93  5 88 20]
[ 0 92  4 88 18]
[ 0 90  2 88 18]
[ 0 91  3 88 18]
[ 0 90  2 88 14]
[ 0 90  2 88 18]
[ 0 92  4 88 18]
[ 0 92  4 88 16]
[ 0 91  3 88 19]
[ 0 92  4 88 18]
[ 0 92  4 88 16]
[ 0 91  3 88 19]
[ 0 93  5 88 17]
[ 0 92  4 88 16]
[ 0 91  3 88 19]
[ 0 93  5 88 17]
[ 0 94  6 88 18]
[ 0 91  3 88 20]
[ 0 94  6 88 18]
[ 0 98 10 88 16]
[ 0 92  4 88 18]
[ 0 96  8 88 16]
[ 0 99 11 88 14]
[ 0 94  6 88 18]
[ 0 93  5 88 14]
[-1 96  8 88  8]
[ 0 91  3 88 18]
[ 0 96  8 88 11]
[-1 96  8 88  8]
[-1 94  6 88 11]
[ 0 96  8 88 11]
[ 0 95  3 92 18]
[ 0 95  3 92 20]
[ 0 96  4 92 20]
[ 0 94  2 92 16]
[ 0 95  3 92 18]
[ 0 95  3 92 20]
[ 0 96  4 92 18]
[ 0 94  2 92 18]
[ 0 95  3 92 18]
[ 0 96  4 92 16]
[ 0 96  4 92 17]
[ 0 96  4 92 20]
[ 0 96  4 92 16]
[ 0 96  4 92 17]
[ 0 96  4 92 20]
[ 0 96  4 92 16]
[ 0 96  4 92 1

100%|██████████| 2/2 [00:01<00:00,  1.14it/s]

[0 4 0 4 4]
[0 4 0 4 6]
[0 6 2 4 6]
[0 4 0 4 4]
[0 4 0 4 6]
[0 6 2 4 6]
[0 4 0 4 4]
[0 4 0 4 6]
[0 6 2 4 6]
[0 4 0 4 2]
[0 4 0 4 5]
[0 6 2 4 6]
[0 4 0 4 2]
[0 4 0 4 5]
[0 6 2 4 6]
[0 4 0 4 2]
[0 4 0 4 5]
[0 6 2 4 6]
[0 4 0 4 4]
[0 4 0 4 6]
[0 6 2 4 6]
[0 4 0 4 4]
[0 4 0 4 6]
[0 6 2 4 6]
[0 4 0 4 4]
[0 4 0 4 6]
[0 6 2 4 6]
[0 4 0 4 3]
[0 4 0 4 6]
[0 6 2 4 3]
[0 4 0 4 3]
[0 4 0 4 6]
[0 6 2 4 3]
[0 4 0 4 4]
[0 4 0 4 6]
[0 6 2 4 6]
[0 4 0 4 4]
[0 4 0 4 6]
[0 6 2 4 6]
[0 4 0 4 4]
[0 4 0 4 6]
[0 6 2 4 6]
[0 4 0 4 2]
[0 4 0 4 5]
[0 6 2 4 6]
[0 4 0 4 2]
[0 4 0 4 5]
[0 6 2 4 3]
[0 4 0 4 2]
[0 4 0 4 5]
[0 6 2 4 3]
[0 4 0 4 4]
[0 4 0 4 6]
[0 6 2 4 6]
[0 4 0 4 4]
[0 4 0 4 6]
[0 6 2 4 6]
[0 4 0 4 4]
[0 4 0 4 6]
[0 6 2 4 6]
[0 4 0 4 3]
[0 4 0 4 6]
[0 6 2 4 3]
[0 4 0 4 3]
[0 4 0 4 3]
[0 6 2 4 3]
[ 0 13  5  8 10]
[ 0 10  2  8 12]
[ 0 13  5  8 12]
[ 0 13  5  8 10]
[0 9 1 8 8]
[0 8 0 8 8]
[ 0 10  2  8  8]
[ 0  8  0  8 10]
[0 9 1 8 6]
[0 8 0 8 6]
[ 0  8  0  8 11]
[ 0 10  2  8 10]
[0 8 0 8 6]
[ 0  8  0  8

In [10]:
scores[0]

100

In [ ]:
! python gui.py

pygame 2.5.2 (SDL 2.28.3, Python 3.9.18)
Hello from the pygame community. https://www.pygame.org/contribute.html
