In [1]:
import sys

# EDIT THIS
sys.path.append('/Users/kenwu/Documents/Github/watai-tetris-getting-started/')

from submission.sample_agent import SelectedAgent
from submission.tetris.game import Game

from tqdm import tqdm
import numpy as np

# Import HyperOpt Library
from hyperopt import tpe, hp, fmin
import numpy as np

import random
import asyncio
import nest_asyncio
nest_asyncio.apply()

%load_ext autoreload
%autoreload 2

In [10]:
weights = [1070.558745981553, 963.7975031106122, 1380.587323768055, 74.34870576097629, -800.7595753505859, 1159.9820521194808, 503.7611272855837, -3.7377129147859023, 14.857216139137405]

In [11]:
scores = []
for seed in range(100):
    GAME_SEED = seed
    agent = SelectedAgent(weights)
    game = Game(agent, seed=GAME_SEED)
    async for item in game.run():
        pass
    scores.append(game.score)

In [27]:
# find the 3 worst seeds
worst_seeds = np.argsort(scores)[:3]
worst_seeds

array([76, 89, 88])

In [28]:
#find thee index of the best 3 scores
best_seeds = np.argsort(scores)[-3:]
best_seeds

array([18,  0, 80])

In [29]:
# find the middle three index
middle_seeds = np.argsort(scores)[48:51]
middle_seeds

array([31, 90, 25])

In [30]:
eval_seeds = np.concatenate([best_seeds, worst_seeds, middle_seeds]) # Joining arr1 and arr2
eval_seeds

array([18,  0, 80, 76, 89, 88, 31, 90, 25])